# Generated by Django 3.2.4 on 2021-07-26 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210725_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.permissiongroup'),
        ),
    ]
