# Generated by Django 3.2.6 on 2021-09-02 13:59

import datetime
from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='month',
            field=month.models.MonthField(default=datetime.datetime(2021, 9, 2, 13, 59, 53, 654546)),
            preserve_default=False,
        ),
    ]
