# Generated by Django 3.2.6 on 2021-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_commission_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
