# Generated by Django 3.2.4 on 2021-07-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
