# Generated by Django 3.2.4 on 2021-07-04 20:59

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_campaign_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='contract',
            field=models.FileField(null=True, upload_to=main.models.get_upload_to),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
