# Generated by Django 3.2.4 on 2021-07-05 20:51

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210704_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, default=main.models.default_end_date, null=True),
        ),
    ]
