# Generated by Django 3.2.4 on 2021-07-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_alter_milestone_department'),
        ('main', '0009_auto_20210715_0706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
