# Generated by Django 3.2.4 on 2021-07-25 22:26

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210725_1050'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.models.CustomUserManager()),
            ],
        ),
    ]
