# Generated by Django 3.2.4 on 2021-07-30 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField()),
                ('iframes', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=4, max_digits=15)),
                ('clicks', models.IntegerField()),
                ('ctr', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ecpm', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ecpc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('conversions', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='desc',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='daily_budget',
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='days',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='planned_start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('campaign_type', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('target_group', models.CharField(max_length=50)),
                ('daily_budget', models.DecimalField(decimal_places=4, max_digits=10)),
                ('daily_budget_left', models.DecimalField(decimal_places=4, max_digits=10)),
                ('added_date', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('number_of_bids', models.IntegerField()),
                ('paused_ads', models.IntegerField()),
                ('number_of_creatives', models.IntegerField()),
                ('number_of_time_targets', models.IntegerField()),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaignstats')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.campaigndata'),
        ),
    ]
