# Generated by Django 3.2.4 on 2021-08-02 07:24

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210731_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='planned_start_date',
            field=models.DateField(blank=True, default=main.models.get_planned_start_date, null=True),
        ),
    ]
