# Generated by Django 3.2.4 on 2021-08-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_campaign_planned_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.campaigndata'),
        ),
    ]
