# Generated by Django 3.2.6 on 2021-09-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_campaign_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_id', models.IntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign', verbose_name='children_set')),
            ],
        ),
    ]
