# Generated by Django 3.2.6 on 2021-09-11 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_minicampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='data',
        ),
        migrations.RemoveField(
            model_name='campaignstats',
            name='last_update',
        ),
        migrations.AddField(
            model_name='campaignstats',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 11, 15, 31, 38, 455114)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaignstats',
            name='minicampaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats_set', to='main.minicampaign'),
        ),
        migrations.AlterField(
            model_name='minicampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='main.campaign'),
        ),
        migrations.DeleteModel(
            name='CampaignData',
        ),
    ]
