# Generated by Django 3.2.6 on 2021-09-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210911_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Pre Active'), (3, 'Finished')], default=2),
        ),
    ]
