# Generated by Django 3.2.6 on 2021-09-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_campaign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstats',
            name='ctr',
        ),
        migrations.RemoveField(
            model_name='campaignstats',
            name='ecpc',
        ),
        migrations.RemoveField(
            model_name='campaignstats',
            name='ecpm',
        ),
        migrations.AddField(
            model_name='campaign',
            name='fee_percentage',
            field=models.IntegerField(default=15),
        ),
    ]
