# Generated by Django 3.2.4 on 2021-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210701_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='order',
            new_name='index',
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
