# Generated by Django 3.2.4 on 2021-07-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210701_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='color',
            field=models.CharField(default='#ffffff', max_length=15),
            preserve_default=False,
        ),
    ]
