# Generated by Django 3.2.4 on 2021-07-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_workflow_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='is_active',
            new_name='started',
        ),
    ]
