# Generated by Django 3.2.4 on 2021-07-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_rename_is_active_workflow_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='is_active',
            new_name='is_external',
        ),
    ]
