# Generated by Django 3.2.4 on 2021-07-05 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_is_active_milestone_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='first_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 20, 25, 45, 480278)),
            preserve_default=False,
        ),
    ]
