# Generated by Django 3.2.4 on 2021-07-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_workflow_first_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='first_date',
            field=models.DateTimeField(),
        ),
    ]
