# Generated by Django 3.2.4 on 2021-07-08 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20210708_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='node',
        ),
        migrations.AddField(
            model_name='node',
            name='task',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='tracker.task'),
            preserve_default=False,
        ),
    ]
