# Generated by Django 3.2.4 on 2021-07-10 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_task_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='started',
        ),
        migrations.AddField(
            model_name='workflow',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 11, 15, 53, 882188)),
            preserve_default=False,
        ),
    ]
