# Generated by Django 3.2.4 on 2021-07-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20210710_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
