# Generated by Django 3.2.4 on 2021-07-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_department'),
        ('tracker', '0016_alter_workflow_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
            preserve_default=False,
        ),
    ]
