# Generated by Django 3.2.4 on 2021-07-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_remove_milestone_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='color',
        ),
    ]
