# Generated by Django 3.2.4 on 2021-07-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_remove_milestone_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('handler', models.CharField(max_length=100)),
            ],
        ),
    ]
