# Generated by Django 3.2.4 on 2021-07-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_completer'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='completer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tracker.completer'),
        ),
    ]
