# Generated by Django 3.2.4 on 2021-07-14 11:21

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20210714_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='upload_dir',
        ),
        migrations.AddField(
            model_name='milestone',
            name='upload_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.get_upload_to),
        ),
    ]
