# Generated by Django 3.2.4 on 2021-07-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_auto_20210714_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='upload_dir',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='upload_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
