# Generated by Django 3.2.4 on 2021-07-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210725_1050'),
        ('tracker', '0027_alter_milestone_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
        ),
    ]
