# Generated by Django 3.2.4 on 2021-07-25 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_milestone_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='completer',
            name='explanation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
